### ISSUE TITLE
Docs at readthedocs is broken

### ISSUE THREAD

**Issue by mgaitan** [cr0hn/aiotasks#1]
the readme links  https://aiotasks.readthedocs.io/  as the doc page, but it raises a 404. 

![image](https://cloud.githubusercontent.com/assets/2355719/24586345/d20d7536-1774-11e7-9f63-3198348324b8.png)

**Comment by cr0hn** [comment]
I just ported the readme.rst file to more format (incomplete still) readthedoc format and I just created and updated the link
